# Generated by Django 4.2.7 on 2023-12-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата создания'),
        ),
    ]
