# Generated by Django 4.2.7 on 2023-11-20 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_category_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100, verbose_name='категория товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_of_change',
            field=models.DateField(default=datetime.datetime(2023, 11, 20, 18, 27, 10, 851177)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2023, 11, 20, 18, 27, 10, 851170)),
        ),
    ]
