# Generated by Django 4.2.7 on 2023-12-18 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_rename_contacts_contact_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_of_change',
            field=models.DateField(default=datetime.datetime(2023, 12, 18, 20, 48, 14, 967831)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2023, 12, 18, 20, 48, 14, 967824)),
        ),
    ]
