# Generated by Django 4.2.7 on 2023-12-19 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_product_date_of_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_of_change',
            field=models.DateField(default=datetime.datetime(2023, 12, 19, 9, 52, 14, 804928)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2023, 12, 19, 9, 52, 14, 804921)),
        ),
    ]
