# Generated by Django 4.2.7 on 2024-01-20 18:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_product_date_of_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_of_change',
            field=models.DateField(default=datetime.datetime(2024, 1, 20, 18, 45, 39, 232974)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2024, 1, 20, 18, 45, 39, 232966)),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products_images/', verbose_name='изображение'),
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.TextField(default='', max_length=100, verbose_name='номер версии')),
                ('version_name', models.TextField(default='', max_length=100, verbose_name='название версии')),
                ('current_version_indicator', models.BooleanField(default=True, verbose_name='признак текущей версии')),
                ('product_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='версия продукта')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'Версии',
            },
        ),
    ]
