# Generated by Django 4.2.7 on 2024-01-20 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_product_date_of_change_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='current_version_indicator',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='product',
            name='date_of_change',
            field=models.DateField(default=datetime.datetime(2024, 1, 20, 19, 39, 14, 588897)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2024, 1, 20, 19, 39, 14, 588890)),
        ),
    ]
