# Generated by Django 4.2.7 on 2024-01-20 20:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_rename_current_version_indicator_version_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_of_change',
            field=models.DateField(default=datetime.datetime(2024, 1, 20, 20, 3, 54, 441982)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2024, 1, 20, 20, 3, 54, 441974)),
        ),
        migrations.AlterField(
            model_name='version',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name=' Текущая версия'),
        ),
        migrations.AlterField(
            model_name='version',
            name='product_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_name',
            field=models.TextField(blank=True, default='', max_length=100, null=True, verbose_name='Название версии'),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.TextField(default='', max_length=100, verbose_name='Номер версии'),
        ),
    ]
