# Generated by Django 4.2.7 on 2024-01-21 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_product_date_of_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_of_change',
            field=models.DateField(default=datetime.datetime(2024, 1, 21, 17, 50, 22, 464707)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2024, 1, 21, 17, 50, 22, 464697)),
        ),
    ]
