# Generated by Django 4.2.7 on 2024-01-25 17:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0017_alter_product_date_of_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='продавец'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_of_change',
            field=models.DateField(default=datetime.datetime(2024, 1, 25, 17, 40, 13, 426572)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2024, 1, 25, 17, 40, 13, 426562)),
        ),
    ]
