# Generated by Django 4.2.7 on 2024-01-26 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_product_owner_alter_product_date_of_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_of_change',
            field=models.DateField(default=datetime.datetime(2024, 1, 26, 9, 34, 9, 191951)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2024, 1, 26, 9, 34, 9, 191944)),
        ),
    ]
